### ISSUE TITLE
may i  get the addresses file

### ISSUE THREAD

**Issue by RedGuitar0** [graymauser/btcposbal2csv#11]
hey 
I'm not a professional programmer. I tried to install hashlib, plyvel and SQLite3 with python3 pip, but they couldn't succeed. Can I get all the address files directly?
thank guitar

**Comment by MCM-Mike** [comment]
you can download a public version here https://blockchair.com/dumps but try to use your own nodes dont trust one public node .

**Comment by RedGuitar0** [comment]
thanks 。



---Original---

**Comment by kenorb** [comment]
See also: https://bitkeys.work/faq.php
