### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by VadimYevtushenko** [graymauser/btcposbal2csv#19]
Hello, gets error with Python 3.8.5 
python3 btcposbal2csv.py /root/.bitcoin/chainstate /root/addresses_with_balance.csv
reading chainstate database
inmem
Traceback (most recent call last):
  File "btcposbal2csv.py", line 201, in <module>
    for address, sat_val, block_height in add_iter:
  File "btcposbal2csv.py", line 98, in in_mem
    for add, val, height in parse_ldb(
  File "/root/btcposbal2csv-master/utils.py", line 317, in parse_ldb
    o_key = db.get((unhexlify("0e00") + "obfuscate_key"))
TypeError: can't concat str to bytes

**Comment by graymauser** [comment]
You appear to use python3. This package is now python2 only. Please use python 2.7.
