### ISSUE TITLE
convert2ripemd160.py return error "'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by dolaor** [graymauser/btcposbal2csv#20]
Hi!

Thank you for sharing your script.

I have tried to run convert2ripemd160.py to convert adresses  to ripemd160 but it is returning an error (see below). The error appears when it hits adresses starting with "bc1" and if I remove them all in the .csv file there is no errors.

On Debian 10 with Python 3.7.3:
Traceback (most recent call last):
  File "convert2ripemd160.py", line 46, in <module>
    process(args.csvin)
  File "convert2ripemd160.py", line 22, in process
    ripemd_encoded = binascii.hexlify(bytearray(script_int))
TypeError: 'NoneType' object is not iterable

On Windows with Python 3.9.2:
Traceback (most recent call last):
  File "C:\Users\Dolaor\Desktop\btcposbal2csv\convert2ripemd160.py", line 46, in <module>
    process(args.csvin)
  File "C:\Users\Dolaor\Desktop\btcposbal2csv\convert2ripemd160.py", line 22, in process
    ripemd_encoded = binascii.hexlify(bytearray(script_int))
TypeError: cannot convert 'NoneType' object to bytearray

Thanks for your help.

**Comment by dolaor** [comment]
It is not an elegant solution but I had to add ",," at the end of each addresses (starting either by 1 or bc1) of an input .csv file containing one address per line. Then run the command "convert2ripemd160.py input.csv > output.csv". The hash160 will be the fourth column of the output file.

**Comment by bsubasic** [comment]
Yes, it would be helpful to have an example output (on Github) from the btcposbal2csv.py script as convert2ripemd160.py expects exactly that format as input. 

Then we would know how to format our input file if we use only convert2ripemd160.py.

By looking into the script code, it is:
address, value_satoshi, last_height
