### ISSUE TITLE
Possible to make it dump txs hashes ?

### ISSUE THREAD

**Issue by Hanoosh** [graymauser/btcposbal2csv#3]
Thank you for this great code, i was wondering is it possible to make it dump transactions hashes ?

**Comment by graymauser** [comment]
It is possible with some code changes, but it is out of scope of this utility.
If I understand correctly, then you can use [bitcoin tools](https://github.com/sr-gi/bitcoin_tools/) for this purpose. Or just parse the leveldb of the UTXO set yourself.
