### ISSUE TITLE
Chainstate end 2021

### ISSUE THREAD

**Issue by gobinll** [graymauser/btcposbal2csv#30]
I got parsed transaction 78299200 but in CSV still 1.5gb
When convert to pickle it only got about 2xxxxxxx only which not completed.
Understand Excell only go for 1048576 only.
How to solve this? Need separate to many CSV then convert to pickle? 
When I run convert to pickes I got about 128pickle but when run Plutus it read total database only 2xxxxxxx only which way out of total 78299200 parsed.
Who can help on this ..thank you.tq

**Comment by ololobin** [comment]
Install EmEditor or use sed.
Or dummy parse every 100k rows

```
echo "$(head -100000 file.csv)" > file1.csv
echo "$(tail -qn +100001  file.csv)" > file.csv
```

```
echo "$(head -100000 file.csv)" > file2.csv
echo "$(tail -qn +100001  file.csv)" > file.csv
```

And do it N times

**Comment by gobinll** [comment]
not happening..sorry i just learning 
read and tried to write to nultiple csv from btcposbal2csv but failed..can gve example how to do with ratatingfilehandler..thanks
