### ISSUE TITLE
Can't concat str to bytes

### ISSUE THREAD

**Issue by marssystems** [graymauser/btcposbal2csv#31]
D:\btcposbal2csv>python btcposbal2csv.py H:\Bitcoin\chainstate addresses_with_balance.csv
reading chainstate database
inmem
Traceback (most recent call last):
  File "btcposbal2csv.py", line 201, in <module>
    for address, sat_val, block_height in add_iter:
  File "btcposbal2csv.py", line 98, in in_mem
    for add, val, height in parse_ldb(
  File "D:\btcposbal2csv\utils.py", line 317, in parse_ldb
    o_key = db.get((unhexlify("0e00") + "obfuscate_key"))
TypeError: can't concat str to bytes

Running on Windows 11 64bit
Bitcoin Core 22.0

**Comment by kenorb** [comment]
See: GH-19.

**Comment by marssystems** [comment]
OK - thanks. I will use Python 2.7.

**Comment by marssystems** [comment]
Using Python 2.7.
