### ISSUE TITLE
Problem "PATH_TO_CHAINSTATE_DIR, OUTFILE"

### ISSUE THREAD

**Issue by ghost** [graymauser/btcposbal2csv#33]
Hi
I run on window
I don't know what happen with below? path problem? Thanks.

D:\btcposbal2csv-master>btcposbal2csv.py chainstate addresses_with_balance.csv
usage: btcposbal2csv.py [-h] [--bitcoin_version BITCOIN_VERSION] [--keep_sqlite PATH_TO_SQLITE_FILE)] [--lowmem]
                        [--P2PKH bool] [--P2SH bool] [--P2PK bool] [--sort ASC/DESC]
                        PATH_TO_CHAINSTATE_DIR OUTFILE
btcposbal2csv.py: error: the following arguments are required: PATH_TO_CHAINSTATE_DIR, OUTFILE

**Comment by graymauser** [comment]
It looks like, that the `chainstate` directory is not located /or does not contain expected files/ under your current directory (`D:\btcposbal2csv-master`). You need to provide correct PATH to your bitcoin chainstate directory as input. 
If your problem persists, please provide more info (your directory layout..).
