### ISSUE TITLE
how to delete this?need help

### ISSUE THREAD

**Issue by VJanabia** [graymauser/btcposbal2csv#37]
1FtZwEZKknoquUb6DyQHFZ6g6oomXJYEcb,**257219114.44438908,740429**
1AQthEXNcQWSfGkUiNAUi6Jj4NYuYLcqdw,**5477.777777777777,572839**
14frN8WdboAvn29bgED9K5zsCTYThRtzDK,**7170.222222222223,586780**

**Comment by marssystems** [comment]
Highlight the text you want to delete and then press the DEL key.

**Comment by VJanabia** [comment]
and I ran 'python convert2ripemd160.py /home/USER/addresses_with_balance.csv ' and no file was generated, is this normal?

**Comment by VJanabia** [comment]
I'm sorry, I've never studied programming at all.
