### ISSUE TITLE
The address seems incomplete

### ISSUE THREAD

**Issue by githubvipuser** [graymauser/btcposbal2csv#7]
I took a few random checks

Block 9901 of 1ly5zpj84hr5wlqsbqk6jb7jsqzkkkcnxb isn't one of them

Can I get a more complete address?

**Comment by graymauser** [comment]
Hi,
This tool only lists addresses with some unspent amount of BTC by analyzing the UTXO set.

The transaction in the block 9901 is "1Ly5ZPJ84hr5wLQsBQk6jb7JSQzkkkCNxB" and this one was spend completely (current balance 0 BTC).

See https://www.blockchain.com/btc/address/1Ly5ZPJ84hr5wLQsBQk6jb7JSQzkkkCNxB
